# Generated by Django 4.2.16 on 2025-08-02 17:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_description', models.TextField(help_text='The original job description provided')),
                ('generated_proposal', models.TextField(help_text='The AI-generated proposal')),
                ('user_id', models.CharField(help_text='ID of the user who requested the proposal', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_title', models.CharField(blank=True, max_length=500, null=True)),
                ('budget_range', models.CharField(blank=True, max_length=100, null=True)),
                ('project_duration', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'job_proposals',
                'ordering': ['-created_at'],
            },
        ),
    ]
