# Generated by Django 4.2.16 on 2025-08-02 19:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('proposal_generator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Project name', max_length=255)),
                ('description', models.TextField(help_text='Detailed project description')),
                ('user_id', models.CharField(help_text='ID of the user who owns this project', max_length=255)),
                ('tags', models.JSONField(default=list, help_text='AI-generated tags for the project')),
                ('ai_summary', models.TextField(blank=True, help_text='AI-generated project summary', null=True)),
                ('technologies', models.JSONField(default=list, help_text='AI-extracted technologies used')),
                ('project_type', models.CharField(blank=True, help_text='AI-determined project type', max_length=100, null=True)),
                ('complexity_level', models.CharField(blank=True, help_text='AI-assessed complexity', max_length=50, null=True)),
                ('embedding_vector', models.JSONField(default=list, help_text='Vector embedding of project description')),
                ('github_url', models.URLField(blank=True, help_text='GitHub repository URL', null=True)),
                ('live_url', models.URLField(blank=True, help_text='Live project URL', null=True)),
                ('app_store_url', models.URLField(blank=True, help_text='App store URL (iOS/Android)', null=True)),
                ('images', models.JSONField(default=list, help_text='List of project image URLs')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Whether to feature this project prominently')),
            ],
            options={
                'db_table': 'portfolio_projects',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id'], name='portfolio_p_user_id_92b8d5_idx'), models.Index(fields=['project_type'], name='portfolio_p_project_541adb_idx'), models.Index(fields=['is_featured'], name='portfolio_p_is_feat_d507be_idx')],
            },
        ),
    ]
