# Generated by Django 4.2.16 on 2025-08-15 14:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('proposal_generator', '0002_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_id', models.CharField(help_text='ID of the generated proposal', max_length=255)),
                ('user_id', models.CharField(help_text='ID of the user who owns this proposal', max_length=255)),
                ('proposal_link', models.URLField(help_text='Link to the Upwork proposal/job')),
                ('connected', models.CharField(help_text='Number of connections or connection status', max_length=100)),
                ('posted_ago', models.CharField(help_text='Time since the job was posted', max_length=100)),
                ('is_viewed', models.BooleanField(default=False, help_text='Whether the proposal has been viewed by client')),
                ('is_hired', models.BooleanField(default=False, help_text='Whether the user was hired for this proposal')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'proposal_tracking',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id'], name='proposal_tr_user_id_61fbe1_idx'), models.Index(fields=['proposal_id'], name='proposal_tr_proposa_22420a_idx'), models.Index(fields=['is_viewed'], name='proposal_tr_is_view_cb5e7e_idx'), models.Index(fields=['is_hired'], name='proposal_tr_is_hire_1b7598_idx')],
            },
        ),
    ]
